# Default configuration

# Particles
particles.origin=0,0.25,0
particles.size=1,1.25,1
particles.resolution=20,25,20
particles.radius=0.02

# Parameters
parameters.threads=0
parameters.delta_time=0.01
parameters.solver_iterations=3
parameters.simulation_steps=1000
parameters.gravity=0,-9.81,0
parameters.rest_density=1010
parameters.relaxation_epsilon=450
parameters.vorticity_gain=0.002
parameters.viscosity_gain=0.00075
parameters.artificial_pressure_gain=0.00025

# Bounds
bounds.domain=2,2,2
bounds.wand_active=true
bounds.wand_radius=1
bounds.wand_strength=30
bounds.boundaries.box=-0.75,-1.45,-1,1.25,0.55,1
bounds.boundaries.box=1.25,-1.75,0,0.75,0.25,2
bounds.boundaries.sphere=1.25,-1.45,1.25,0.55

# Visuals
visuals.window_width=800
visuals.window_height=600
visuals.camera_position=0,3,8
visuals.camera_target=0,-0.4,0
visuals.mouse_orbit_sensitivity=0.003
visuals.mouse_pan_sensitivity=0.002
visuals.mouse_wheel_sensitivity=0.01
